name: my_portfolio
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  skeletonizer: ^1.1.1
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_intl:
  enabled: true
  # -------------------------------
flutter:

  uses-material-design: true
  assets:
    - assets/images/
