name: my_portfolio
description: "A new Flutter project."

publish_to: 'none'
# flutter build web --release
# firebase deploy --only hosing
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  get_it: ^7.7.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_smart_dialog: ^4.9.6+1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  skeletonizer: ^1.1.1
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_intl:
  enabled: true
  # -------------------------------
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
