name: my_portfolio
description: "A new Flutter project."

publish_to: 'none'
# flutter build web --release
# firebase deploy --only hosing
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_bootstrap: ^2.0.0
  flutter_bootstrap5: ^1.1.1+1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.0
  flutter_smart_dialog: ^4.9.6+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  intl: ^0.19.0
  skeletonizer: ^1.1.1
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_intl:
  enabled: true
# -------------------------------
#flutter pub get
#flutter pub run flutter_launcher_icons
flutter_icons:
  # android: true
  # ios: true
  # image_path: "assets/images/the_flutter_image.png"
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/images/the_flutter_image.png"
  # web:
  #   generate: true
  #   image_path:  "assets/images/the_flutter_image.png"
  #   background_color: "#ffffff"
  # -------------------------------
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
