// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUQO6fx3rcL2taA2gVmN73wv1TEG9lyo',
    appId: '1:781735671229:web:ece512945da6918a31ced4',
    messagingSenderId: '781735671229',
    projectId: 'ziad-dev-e015d',
    authDomain: 'ziad-dev-e015d.firebaseapp.com',
    storageBucket: 'ziad-dev-e015d.appspot.com',
    measurementId: 'G-2WF7L75DD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3PUKlQYOI22sGwKXFUqgCL795QW2-lZA',
    appId: '1:781735671229:android:d0e45b4a5e6e2fa331ced4',
    messagingSenderId: '781735671229',
    projectId: 'ziad-dev-e015d',
    storageBucket: 'ziad-dev-e015d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8QKAtnoPxdyt6esEFIFkJQ0Ml95v8NgI',
    appId: '1:781735671229:ios:ef5b7f7cc17a6eb831ced4',
    messagingSenderId: '781735671229',
    projectId: 'ziad-dev-e015d',
    storageBucket: 'ziad-dev-e015d.appspot.com',
    iosBundleId: 'com.example.myPortofolio',
  );
}
